from __future__ import annotations

from typing import Any

from .config import DQNConfig

# UI display strings and reward defaults for the DQN bot.
# Separated from config.py so the algorithm module stays free of presentation concerns.
BOT_SPEC: dict[str, Any] = {
    "type": "DQNBot",
    "class": DQNConfig,
    "tabs": [
        {"key": "general", "label": "General"},
        {"key": "core", "label": "Core"},
        {"key": "encoding", "label": "Encoding"},
        {"key": "warmup", "label": "Warmup/Planner"},
        {"key": "rewards", "label": "Rewards"},
    ],
    "params": {
        "Learning Rate": "learningRate",
        "Discount Factor": "discountFactor",
        "Epsilon Start": "epsilonStart",
        "Epsilon End": "epsilonEnd",
        "Epsilon Decay Steps": "epsilonDecaySteps",
        "Replay Capacity": "replayCapacity",
        "Batch Size": "batchSize",
        "Train Frequency": "trainFrequency",
        "Target Update Frequency": "targetUpdateFrequency",
        "Hidden Size": "hiddenSize",
        "Max Steps Per Episode": "maxStepsPerEpisode",
        "Use Rich Encoding (0/1)": "useRichEncoding",
        "Use Position In State (0/1)": "usePositionInState",
        "Use Entity Observation (0/1)": "useEntityObservation",
        "Use Enemy Observation (0/1)": "useEnemyObservation",
        "Use Attack Actions (0/1)": "useAttackActions",
        "Push Cooldown Steps": "pushCooldownSteps",
        "Use Macro Actions (0/1)": "useMacroActions",
        "Use Macro-Only Policy (0/1)": "useMacroOnlyPolicy",
        "Dual-Record Primitive Policy (0/1)": "dualRecordPrimitivePolicy",
        "Use Hierarchical Policy (0/1)": "useHierarchicalPolicy",
        "Neural Map Width": "neuralMapWidth",
        "Neural Map Height": "neuralMapHeight",
        "Neural Map Pool Size": "neuralMapPoolSize",
        "Immediate Reversal Penalty": "immediateReversalPenalty",
        "Repeat Visit Penalty Scale": "repeatVisitPenaltyScale",
        "No Progress Penalty": "noProgressPenalty",
        "No Progress Patience Factor": "noProgressPatienceFactor",
        "Min No Progress Steps": "minNoProgressSteps",
        "Max No Progress Steps": "maxNoProgressSteps",
        "Reward Clip Min": "rewardClipMin",
        "Reward Clip Max": "rewardClipMax",
        "Map Embed Dim": "mapEmbedDim",
        "Checkpoint Frequency": "checkpointFrequency",
        "Evaluation Frequency": "evaluationFrequency",
        "Diagnostics Frequency": "diagnosticsFrequency",
    },
    "paramTabs": {
        "learningRate": "core",
        "discountFactor": "core",
        "epsilonStart": "core",
        "epsilonEnd": "core",
        "epsilonDecaySteps": "core",
        "replayCapacity": "core",
        "batchSize": "core",
        "trainFrequency": "core",
        "targetUpdateFrequency": "core",
        "hiddenSize": "core",
        "maxStepsPerEpisode": "core",
        "useRichEncoding": "encoding",
        "usePositionInState": "encoding",
        "useEntityObservation": "encoding",
        "useEnemyObservation": "encoding",
        "useAttackActions": "general",
        "pushCooldownSteps": "general",
        "useMacroActions": "general",
        "useMacroOnlyPolicy": "general",
        "dualRecordPrimitivePolicy": "general",
        "useHierarchicalPolicy": "general",
        "neuralMapWidth": "encoding",
        "neuralMapHeight": "encoding",
        "neuralMapPoolSize": "encoding",
        "immediateReversalPenalty": "rewards",
        "repeatVisitPenaltyScale": "rewards",
        "noProgressPenalty": "rewards",
        "noProgressPatienceFactor": "rewards",
        "minNoProgressSteps": "rewards",
        "maxNoProgressSteps": "rewards",
        "rewardClipMin": "rewards",
        "rewardClipMax": "rewards",
        "mapEmbedDim": "encoding",
        "checkpointFrequency": "core",
        "evaluationFrequency": "core",
        "diagnosticsFrequency": "core",
    },
    "paramHelp": {
        "learningRate": "Step size used by the optimizer when updating network weights.",
        "discountFactor": "How much future reward matters relative to immediate reward.",
        "epsilonStart": "Initial exploration rate used at the start of training.",
        "epsilonEnd": "Lowest exploration rate allowed after epsilon decay finishes.",
        "epsilonDecaySteps": "Number of environment steps used to decay epsilon from start to end.",
        "replayCapacity": "Maximum number of transitions stored in replay memory.",
        "batchSize": "Number of replay samples used per training update.",
        "trainFrequency": "How often to run a gradient update, measured in environment steps.",
        "targetUpdateFrequency": "How often to sync the target network from the online network.",
        "hiddenSize": "Width of the fully connected layers in the DQN model.",
        "maxStepsPerEpisode": "Hard cap on steps before an episode is terminated.",
        "useRichEncoding": "Include the neural map encoding instead of relying only on flat local features.",
        "usePositionInState": "Include the bot's absolute position in the state features.",
        "useEntityObservation": "Include observed entities and environment context in the state features.",
        "useEnemyObservation": "Append global enemy-scan features (nearest enemy distance, direction, and line-of-sight) to the state. Requires enemies to be present in the maze.",
        "useMacroActions": "Enable multi-step option actions in addition to primitive moves.",
        "useMacroOnlyPolicy": "Restrict the learned policy to macro-actions only.",
        "dualRecordPrimitivePolicy": "Also train a primitive-only side policy while macro training is active.",
        "useHierarchicalPolicy": "Use a high-level option chooser with a low-level primitive controller.",
        "neuralMapWidth": "Width of the local neural map window encoded around the bot.",
        "neuralMapHeight": "Height of the local neural map window encoded around the bot.",
        "neuralMapPoolSize": "Pooling size used when compressing the neural map representation.",
        "immediateReversalPenalty": "Penalty added when the bot immediately undoes its previous move on the next step.",
        "repeatVisitPenaltyScale": "Penalty added each time the bot steps onto a cell it already visited earlier in the same episode. Penalty values should be negative, for example -2.",
        "noProgressPenalty": "Extra penalty applied when the bot hits the no-progress limit. In the current runtime, no progress means too many consecutive revisit steps.",
        "noProgressPatienceFactor": "Multiplier used to compute the allowed no-progress window in steps: optimal_path_length x this factor, then clamped by the min/max settings below. This is step-count based, not time based.",
        "minNoProgressSteps": "Minimum allowed no-progress window, measured in consecutive steps. Even if the patience-factor formula gives a smaller value, the runtime will use at least this many steps.",
        "maxNoProgressSteps": "Maximum allowed no-progress window, measured in consecutive steps. Even if the patience-factor formula gives a larger value, the runtime will cap it here.",
        "rewardClipMin": "Optional lower bound for reward clipping. Leave both clip fields blank to disable clipping.",
        "rewardClipMax": "Optional upper bound for reward clipping. Leave both clip fields blank to disable clipping.",
        "mapEmbedDim": "Size of the learned embedding produced from the neural map CNN.",
        "checkpointFrequency": "Save a training checkpoint every N episodes. Set 0 to disable periodic saves.",
        "evaluationFrequency": "Run an evaluation episode every N training episodes. Set 0 to disable.",
        "diagnosticsFrequency": "Emit diagnostics every N steps or updates, depending on the runtime hook.",
    },
    "negativeParams": [
        "immediateReversalPenalty",
        "repeatVisitPenaltyScale",
        "noProgressPenalty",
    ],
    "rewards": {
        "goal_reached": 1000,
        "hit_wall": -100,
        "revisit_optimal_path": 0,
        "revisit_non_optimal_path": 0,
        "move_in_optimal_path": 0,
        "see_goal_new_location": 0,
        "see_goal_revisit": 0,
        "per_move_penalty": -1,
        "enemy_contact": -250,
        "death_by_enemy": -1000,
        "enemy_killed": 500,
    },
    "rewardLabels": {
        "goal_reached": "Goal Reached Reward",
        "hit_wall": "Hit Wall Penalty",
        "revisit_optimal_path": "Revisit Optimal Path Penalty",
        "revisit_non_optimal_path": "Revisit Non-Optimal Path Penalty",
        "move_in_optimal_path": "Move In Optimal Path Reward",
        "see_goal_new_location": "See Goal New Location Reward",
        "see_goal_revisit": "See Goal Revisit Reward",
        "per_move_penalty": "Per Move Penalty",
        "enemy_contact": "Enemy Contact Penalty",
        "death_by_enemy": "Death By Enemy Penalty",
        "enemy_killed": "Enemy Killed Reward",
    },
    "rewardSections": [
        {"title": "Value Bounds", "keys": ["rewardClipMin", "rewardClipMax"]},
        {
            "title": "Penalties And Progress Rules",
            "keys": [
                "immediateReversalPenalty",
                "repeatVisitPenaltyScale",
                "noProgressPenalty",
                "noProgressPatienceFactor",
                "minNoProgressSteps",
                "maxNoProgressSteps",
                "hit_wall",
                "revisit_optimal_path",
                "revisit_non_optimal_path",
                "per_move_penalty",
                "enemy_contact",
                "death_by_enemy",
            ],
        },
        {
            "title": "Combat",
            "keys": ["enemy_killed"],
        },
        {
            "title": "Positive Rewards",
            "keys": [
                "goal_reached",
                "move_in_optimal_path",
                "see_goal_new_location",
                "see_goal_revisit",
            ],
        },
    ],
    "rewardHelp": {
        "goal_reached": "Reward granted when the bot reaches the maze goal.",
        "hit_wall": "Penalty applied when the bot attempts to move into a wall.",
        "revisit_optimal_path": "Reward or penalty for revisiting a tile on the optimal path.",
        "revisit_non_optimal_path": "Reward or penalty for revisiting a tile off the optimal path.",
        "move_in_optimal_path": "Reward for taking a step that stays on the optimal path.",
        "see_goal_new_location": "Reward when the bot sees the goal from a new location.",
        "see_goal_revisit": "Reward when the bot sees the goal again from a location it has already used.",
        "per_move_penalty": "Small per-step cost to discourage wandering and long solutions.",
        "enemy_contact": "Penalty applied when an enemy catches the bot during the enemy turn.",
        "death_by_enemy": "Additional terminal penalty applied when the episode ends because an enemy caught the bot.",
        "enemy_killed": "Reward granted each time the bot kills an enemy (via attack or push-into-wall).",
        "useAttackActions": "Enable directional attack actions (attack_up/down/left/right). Adds 4 new actions that kill adjacent enemies in 1 hit. Incompatible with old checkpoints.",
        "pushCooldownSteps": "Cooldown (in steps) between pushes. Bot cannot push-displace an enemy until this many steps have passed since the last push.",
    },
    "negativeRewards": [
        "hit_wall",
        "revisit_optimal_path",
        "revisit_non_optimal_path",
        "per_move_penalty",
        "enemy_contact",
        "death_by_enemy",
    ],
}
